[colors.bright]
black = "0x000b1e"
blue = "0x18978F"
cyan = "0x34e2e2"
green = "0xffc0cb"
magenta = "0x9b6a90"
red = "0xA10035"
white = "0xd7d7d5"
yellow = "0xEF5B0C"

[colors.cursor]
cursor = "0x34e2e2"
text = "0x000b1e"

[colors.dim]
black = "#000b1e"
blue = "0x18978F"
# bright_foreground = "0xffc0cb"
cyan = "0x34e2e2"
# dim_foreground = "0xffc0cb"
green = "#ffc0cb"
magenta = "0x9b6a90"
red = "#A10035"
white = "#d7d7d5"
yellow = "#EF5B0C"

# [colors.dim.focused_match]
# background = "0x0abdc6"
# foreground = "0x000b1e"

# [colors.dim.matches]
# background = "0x0abdc6"
# foreground = "0x000b1e"

[colors.footer_bar]
background = "0x9b6a90"
foreground = "0x0abdc6"

[colors.normal]
black = "0x000b1e"
blue = "0x18978f"
cyan = "0x34e2e2"
green = "0xffc0cb"
magenta = "0x9b6a90"
red = "0xA10035"
white = "0xd7d7d5"
yellow = "0xEF5B0C"

[colors.primary]
background = "0x000b1e"
foreground = "0x5a8f7b"

[font]
size = 12.0

# [font.normal]
# family = "SourceCodePro"
# style = "Semibold"
