f cycle video down
j cycle video
d cycle audio down
k cycle audio
s cycle sub down
l cycle sub

m add sub-pos +1
u add sub-pos -1

enter cycle fullscreen
i script-binding stats/display-stats-toggle
_ cycle deinterlace

q quit-watch-later
Q quit
