vo=gpu-next
# vo=gpu
gpu-api=vulkan
hwdec=nvdec

loop-file=inf
# fullscreen=yes
force-window=yes
geometry=2880x1620
# geometry=3360x1890
border=no

sid=1
watch-later-options-remove=sub-pos
# osc=yes
# sub-pos=105
osc=no
sub-pos=110

osd-bar=no
osd-on-seek=no
# osd-on-seek=msg
# osd-duration=3000

[4k]
target-prim=bt.2020
target-trc=pq
