vo=gpu-next
gpu-api=vulkan
hwdec=nvdec

geometry=2880x1620
border=no
force-window=yes

loop-file=inf
osd-bar=no
osd-color='#ffc0cb'
script-opts=show-osc-on-seek=no

[check]
geometry=3360x1890

[inspect]
geometry=3360x1890
script-opts=show-stats=yes

[inspect-quality]
geometry=3360x1890
osc=no
fullscreen=yes

[watch]
geometry=2880x1620
osc=no
script-opts=show-osc-on-seek=yes
sid=1

[4k]
target-prim=bt.2020
target-trc=pq
