vo=gpu-next
# vo=gpu
gpu-api=vulkan
hwdec=nvdec

loop-file=inf
force-window=yes
geometry=2880x1620
# geometry=3360x1890
border=no

osd-bar=no
osd-on-seek=no
# osd-on-seek=msg
# osd-duration=3000
osd-color='#ffc0cb'

sid=1
# watch-later-options-remove=sub-pos

[watch]
geometry=2880x1620
osc=no

[inspect]
geometry=3360x1890
osc=yes
script-opts=show-stats=yes

[inspect-playlist]
geometry=3360x1890
osc=yes

[inspect-fs]
geometry=3360x1890
osc=yes
script-opts=show-stats=yes
fullscreen=yes

[inspect-quality]
geometry=3360x1890
osc=yes
fullscreen=yes

[4k]
target-prim=bt.2020
target-trc=pq
