visibility=always
visibility_modes=never_always
timems=yes
timetotal=yes
tooltipborder=0
windowcontrols=no
# boxvideo=yes

# background_color='000b1e'
timecode_color='5A8F7B'
title_color='ffc0cb'
time_pos_color='ffc0cb'
time_pos_outline_color='000000'
buttons_color='5A8F7B'
top_buttons_color='5A8F7B'
