visibility=always
visibility_modes=never_always
timems=yes
timetotal=yes
tooltipborder=0
windowcontrols=no
# boxvideo=yes

# background_color='000b1e'
timecode_color='18978f'
title_color='ef5b0c'
time_pos_color='ffc0cb'
time_pos_outline_color='000000'
buttons_color='18978f'
top_buttons_color='18978f'
